### ISSUE TITLE
numpy error

### ISSUE THREAD

**Issue by DomenicoSkyWalker89** [cliffren/PENCIL#5]
Dear all,

Thanks to share PENCIL code, it represent a very interesting tool.

I'm new with python -> R link (generally I used only R). Running your code I encountered this error (probably linked with numpy):

dataset: PENCIL_tutorial_1, expr_id: 0.0.1
scheme: ce, Sigmoid
searching c...
cuda is not available, and cpu is used.
cmin:0.000, cmax:2.000, c:1.000, rejected 0 cells.
cuda is not available, and cpu is used.
cmin:0.000, cmax:1.000, c:0.500, rejected 3626 cells.
cuda is not available, and cpu is used.
cmin:0.000, cmax:0.500, c:0.250, rejected 6249 cells.
cuda is not available, and cpu is used.
cmin:0.250, cmax:0.500, c:0.375, rejected 4561 cells.
cuda is not available, and cpu is used.
cmin:0.250, cmax:0.375, c:0.312, rejected 5540 cells.
cuda is not available, and cpu is used.
cmin:0.250, cmax:0.312, c:0.281, rejected 5905 cells.
cuda is not available, and cpu is used.
cmin:0.281, cmax:0.312, c:0.297, rejected 5796 cells.
searched c: 0.296875
pretrain 500 epochs...
cuda is not available, and cpu is used.
epoch=0, loss=0.3839, mean_e=0.4755, mean_r=-0.0433, L1_reg=21.3148
epoch=20, loss=0.3407, mean_e=0.4753, mean_r=-0.5820, L1_reg=27.6189
epoch=40, loss=0.3403, mean_e=0.4758, mean_r=-0.6453, L1_reg=27.5346
epoch=60, loss=0.3381, mean_e=0.4769, mean_r=-0.6720, L1_reg=31.8458
epoch=80, loss=0.3362, mean_e=0.4787, mean_r=-0.5778, L1_reg=36.8783
epoch=100, loss=0.3337, mean_e=0.4812, mean_r=-0.4753, L1_reg=43.5506
epoch=120, loss=0.3320, mean_e=0.4830, mean_r=-0.4532, L1_reg=51.4539
epoch=140, loss=0.3306, mean_e=0.4826, mean_r=-0.4460, L1_reg=59.1397
epoch=160, loss=0.3294, mean_e=0.4822, mean_r=-0.4380, L1_reg=65.9310
epoch=180, loss=0.3281, mean_e=0.4814, mean_r=-0.4431, L1_reg=72.2466
epoch=200, loss=0.3268, mean_e=0.4806, mean_r=-0.4358, L1_reg=78.7376
epoch=220, loss=0.3256, mean_e=0.4798, mean_r=-0.4332, L1_reg=85.0496
epoch=240, loss=0.3245, mean_e=0.4786, mean_r=-0.4193, L1_reg=91.7653
epoch=260, loss=0.3234, mean_e=0.4765, mean_r=-0.4148, L1_reg=97.8540
epoch=280, loss=0.3227, mean_e=0.4758, mean_r=-0.4132, L1_reg=103.7564
epoch=300, loss=0.3220, mean_e=0.4745, mean_r=-0.4121, L1_reg=109.5119
epoch=320, loss=0.3214, mean_e=0.4737, mean_r=-0.4155, L1_reg=115.1696
epoch=340, loss=0.3207, mean_e=0.4725, mean_r=-0.4143, L1_reg=120.6323
epoch=360, loss=0.3198, mean_e=0.4711, mean_r=-0.4079, L1_reg=126.2049
epoch=380, loss=0.3193, mean_e=0.4705, mean_r=-0.4042, L1_reg=131.7096
epoch=400, loss=0.3187, mean_e=0.4700, mean_r=-0.3962, L1_reg=136.9384
epoch=420, loss=0.3182, mean_e=0.4694, mean_r=-0.3931, L1_reg=142.0303
epoch=440, loss=0.3178, mean_e=0.4686, mean_r=-0.3934, L1_reg=147.0370
epoch=460, loss=0.3172, mean_e=0.4671, mean_r=-0.3886, L1_reg=151.9483
epoch=480, loss=0.3167, mean_e=0.4657, mean_r=-0.3819, L1_reg=156.8935
---train time: 186.08103203773499 seconds ---

cuda is not available, and cpu is used.
Number of examples rejected= 4363 / 6350
num_of_rejcted
class_2           1531
class_3           1422
class_1           1410
Name: count, dtype: int64
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/domenicolotartaro/PENCIL/pencil/pencil.py", line 271, in fit_transform
    h, r = self.transform(data, labels, savefig=savefig, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/domenicolotartaro/PENCIL/pencil/pencil.py", line 241, in transform
    h, r = test[self.mode](
           ^^^^^^^^^^^^^^^^
  File "/Users/domenicolotartaro/PENCIL/pencil/pencil_evaluator.py", line 266, in mul_class_test
    res_df = res_to_labels(result_info, anno_file, class_names=class_names, keep_origin_label_for_rest=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/domenicolotartaro/PENCIL/pencil/utils.py", line 109, in res_to_labels
    h = np.array(h, dtype=np.int)
                          ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

######################################################################

the code I used:

import numpy
import os

os.environ['CUDA_VISIBLE_DEVICES'] = '-1' #select a gpu id, otherwise set to '-1'.

from pencil import *

# For recording the results. 
data_name = 'PENCIL_tutorial_1'
expr_id = '0.0.1'

data = r.exp_data.T.copy()
labels = np.array(r.labels_2_ids, dtype=int)

mode = 'multi-classification'
pencil = Pencil(mode, select_genes=True, seed=1234, data_name=data_name, expr_id=expr_id)
pred, confidence = pencil.fit_transform(
    data, labels, 
    test=True, 
    shuffle_rate=1/4,
    lambda_L1=1e-5, 
    lambda_L2=1e-3, 
    lr=0.01,  
    class_weights=None,
    class_names=r.class_names, 
    plot_show=False
    )

Have you any suggestion on how to solve it?

ps: I'm using cpu because my laptop did not have GPU, but my workstation have it.

Best,

Domenico

**Comment by cliffren** [comment]
This error is indeed caused by numpy. "np.int" is deprecated in higher versions of numpy.  It can be fixed by replacing all **_"np.int"_** with **_"int"_** in **_"pencil/utils.py"_**. I've also updated it, so you can download the latest code file.

**Comment by DomenicoSkyWalker89** [comment]
Thanks for the rapid replay.

I downloaded the newest utils.py file replacing the oldest one within the folder but unfortunately already did not work (same error).

Did I do something wrong? Do I have to reinstall it?

Best,
Domenico

**Comment by cliffren** [comment]
Thanks for your feedback. 

Have you restarted your R session or Rstudio? This will reload the python environment, which is necessary. 

If you used _"**pip install -e .**"_ when installing the package, there is no need to reinstall. But you can still try,
```
cd PENCIL
pip uninstall pencil
pip install -e .
```

Hope it's helpful.
Best, 
Tao Ren

**Comment by DomenicoSkyWalker89** [comment]
After reinstalling it works perfectly!! Thanks a lot.Best,DomenicoIl giorno 10 ago 2023, alle ore 02:13, Tao Ren ***@***.***> ha scritto:﻿
Thanks for your feedback.
Have you restarted your R session or Rstudio? This will reload the python environment, which is necessary.
If you used "pip install -e ." when installing the package, there is no need to reinstall. But you can still try,
cd PENCIL
pip uninstall pencil
pip install -e .

Hope it's helpful.
Best,
Tao Ren
